apiVersion: v1
kind: Service
metadata:
  name: nodeportlister
  namespace: kube-system
  labels:
    k8s-app: nodeportlister
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    k8s-app: nodeportlister
